export const skills = ["Node.js", "Machine Learning", "MySQL", "Cryptography", "Blockchain", "Deep learning", "Assisted reality and virtual reality", "PhP", "HTML", "CSS", "Java", "JavaScript", "C", "C++", "Python", "MongoDB", "Android App", "IOT", "ChatBots", "OpenCV", "Cloud Computing"];

export const jobroles = ["Data scientist", "Entry-level engineer", "UX designer", "Quality assurance", "Salesforce developer", "Security analyst", "Full stack developer", "Mobile Developer", "Web Developers", "Programmer", "Network Engineer", "Graphic Designer", "3D/2D Animator", "Designer", "Social Media Expert", "Animator", "Backend Developer"];

export const mockData = [
	{
		"id": 1,
		"company_name": "Duis Risus Inc.",
		"full_name": "Wallace",
		"location": "Montenegro",
		"annual_revenue": "€146,681",
		"email": "et.tristique.pellentesque@mi.ca",
		"number_of_employees": 25438,
		"freelancers_needed": 9,
		"months_of_work": 3
	},
	{
		"id": 2,
		"company_name": "Vivamus Sit Corporation",
		"full_name": "Donovan",
		"location": "Bangladesh",
		"annual_revenue": "€103,801",
		"email": "Maecenas@duilectusrutrum.com",
		"number_of_employees": 48423,
		"freelancers_needed": 5,
		"months_of_work": 1
	},
	{
		"id": 3,
		"company_name": "Urna Justo Limited",
		"full_name": "Jameson",
		"location": "Malawi",
		"annual_revenue": "€102,711",
		"email": "libero@vitaealiquameros.net",
		"number_of_employees": 61576,
		"freelancers_needed": 6,
		"months_of_work": 5
	},
	{
		"id": 4,
		"company_name": "Sem LLP",
		"full_name": "Desiree",
		"location": "Monaco",
		"annual_revenue": "€197,179",
		"email": "ipsum.dolor@Innecorci.org",
		"number_of_employees": 9913,
		"freelancers_needed": 8,
		"months_of_work": 10
	},
	{
		"id": 5,
		"company_name": "Feugiat Company",
		"full_name": "Rana",
		"location": "Saint Lucia",
		"annual_revenue": "€173,133",
		"email": "tellus.faucibus.leo@musDonec.edu",
		"number_of_employees": 74837,
		"freelancers_needed": 9,
		"months_of_work": 4
	},
	{
		"id": 6,
		"company_name": "Nisi Cum Institute",
		"full_name": "Ila",
		"location": "Slovenia",
		"annual_revenue": "€105,148",
		"email": "egestas@bibendum.ca",
		"number_of_employees": 67501,
		"freelancers_needed": 2,
		"months_of_work": 6
	},
	{
		"id": 7,
		"company_name": "Sed Dui Fusce Foundation",
		"full_name": "Tarik",
		"location": "Belgium",
		"annual_revenue": "€194,672",
		"email": "velit.dui.semper@quis.org",
		"number_of_employees": 78121,
		"freelancers_needed": 2,
		"months_of_work": 10
	},
	{
		"id": 8,
		"company_name": "Aliquet Corp.",
		"full_name": "Brynne",
		"location": "South Africa",
		"annual_revenue": "€129,015",
		"email": "ultrices@malesuadafamesac.net",
		"number_of_employees": 64662,
		"freelancers_needed": 8,
		"months_of_work": 10
	},
	{
		"id": 9,
		"company_name": "Iaculis Enim Ltd",
		"full_name": "Mara",
		"location": "Qatar",
		"annual_revenue": "€176,979",
		"email": "tempus.mauris.erat@Mauris.com",
		"number_of_employees": 96916,
		"freelancers_needed": 10,
		"months_of_work": 5
	},
	{
		"id": 10,
		"company_name": "Natoque Ltd",
		"full_name": "Alec",
		"location": "Panama",
		"annual_revenue": "€185,287",
		"email": "Sed.nec.metus@nibhQuisque.org",
		"number_of_employees": 15745,
		"freelancers_needed": 5,
		"months_of_work": 9
	},
	{
		"id": 11,
		"company_name": "Ultrices Mauris Company",
		"full_name": "Lila",
		"location": "China",
		"annual_revenue": "€151,022",
		"email": "Mauris.non.dui@eu.com",
		"number_of_employees": 3225,
		"freelancers_needed": 10,
		"months_of_work": 10
	},
	{
		"id": 12,
		"company_name": "Adipiscing Inc.",
		"full_name": "Idola",
		"location": "Guinea-Bissau",
		"annual_revenue": "€108,622",
		"email": "urna.et@DonecnibhQuisque.co.uk",
		"number_of_employees": 59627,
		"freelancers_needed": 2,
		"months_of_work": 1
	},
	{
		"id": 13,
		"company_name": "Amet Luctus Inc.",
		"full_name": "Channing",
		"location": "Lithuania",
		"annual_revenue": "€154,077",
		"email": "Quisque.ac.libero@Donec.net",
		"number_of_employees": 91245,
		"freelancers_needed": 8,
		"months_of_work": 8
	},
	{
		"id": 14,
		"company_name": "Tellus Phasellus Associates",
		"full_name": "Adria",
		"location": "Angola",
		"annual_revenue": "€179,038",
		"email": "Donec.nibh.Quisque@Etiam.edu",
		"number_of_employees": 24012,
		"freelancers_needed": 10,
		"months_of_work": 7
	},
	{
		"id": 15,
		"company_name": "Elit Nulla Corp.",
		"full_name": "Beck",
		"location": "China",
		"annual_revenue": "€131,266",
		"email": "volutpat@malesuadafamesac.org",
		"number_of_employees": 21859,
		"freelancers_needed": 1,
		"months_of_work": 4
	},
	{
		"id": 16,
		"company_name": "Mauris Rhoncus Id LLC",
		"full_name": "Forrest",
		"location": "Barbados",
		"annual_revenue": "€179,969",
		"email": "tortor@arcuetpede.com",
		"number_of_employees": 64606,
		"freelancers_needed": 5,
		"months_of_work": 4
	},
	{
		"id": 17,
		"company_name": "Ante Ipsum Primis Industries",
		"full_name": "Christine",
		"location": "Antigua and Barbuda",
		"annual_revenue": "€116,652",
		"email": "lorem.ac.risus@sociisnatoque.co.uk",
		"number_of_employees": 13879,
		"freelancers_needed": 2,
		"months_of_work": 5
	},
	{
		"id": 18,
		"company_name": "Vitae Odio Sagittis Company",
		"full_name": "Harper",
		"location": "Fiji",
		"annual_revenue": "€155,921",
		"email": "diam@convallisdolor.net",
		"number_of_employees": 2318,
		"freelancers_needed": 10,
		"months_of_work": 9
	},
	{
		"id": 19,
		"company_name": "Magna LLC",
		"full_name": "Wing",
		"location": "Austria",
		"annual_revenue": "€199,792",
		"email": "ac@luctusCurabituregestas.edu",
		"number_of_employees": 24271,
		"freelancers_needed": 2,
		"months_of_work": 3
	},
	{
		"id": 20,
		"company_name": "Duis LLC",
		"full_name": "Christian",
		"location": "Haiti",
		"annual_revenue": "€178,270",
		"email": "posuere@Donecnibh.edu",
		"number_of_employees": 82439,
		"freelancers_needed": 10,
		"months_of_work": 7
	},
	{
		"id": 21,
		"company_name": "Proin Vel PC",
		"full_name": "Ariel",
		"location": "Dominica",
		"annual_revenue": "€139,429",
		"email": "eget.dictum.placerat@idnunc.com",
		"number_of_employees": 43906,
		"freelancers_needed": 2,
		"months_of_work": 7
	},
	{
		"id": 22,
		"company_name": "Sit Amet Luctus PC",
		"full_name": "Dean",
		"location": "Antarctica",
		"annual_revenue": "€107,649",
		"email": "Aliquam@lobortis.com",
		"number_of_employees": 84811,
		"freelancers_needed": 8,
		"months_of_work": 7
	},
	{
		"id": 23,
		"company_name": "Mattis Integer Company",
		"full_name": "Amy",
		"location": "Afghanistan",
		"annual_revenue": "€199,297",
		"email": "blandit.mattis@diamlorem.co.uk",
		"number_of_employees": 94376,
		"freelancers_needed": 6,
		"months_of_work": 3
	},
	{
		"id": 24,
		"company_name": "Est Company",
		"full_name": "Yoshio",
		"location": "Austria",
		"annual_revenue": "€143,869",
		"email": "Morbi.non@feugiatSednec.edu",
		"number_of_employees": 30799,
		"freelancers_needed": 3,
		"months_of_work": 5
	},
	{
		"id": 25,
		"company_name": "Cum Sociis Natoque LLC",
		"full_name": "Jasmine",
		"location": "Liechtenstein",
		"annual_revenue": "€198,349",
		"email": "enim@faucibusMorbivehicula.edu",
		"number_of_employees": 59129,
		"freelancers_needed": 1,
		"months_of_work": 2
	},
	{
		"id": 26,
		"company_name": "Velit Quisque Varius Corp.",
		"full_name": "Sophia",
		"location": "Gambia",
		"annual_revenue": "€137,235",
		"email": "cursus.luctus.ipsum@sem.edu",
		"number_of_employees": 74213,
		"freelancers_needed": 9,
		"months_of_work": 10
	},
	{
		"id": 27,
		"company_name": "In Consectetuer Ipsum Inc.",
		"full_name": "Ina",
		"location": "Ireland",
		"annual_revenue": "€124,921",
		"email": "euismod.enim@loremtristiquealiquet.edu",
		"number_of_employees": 32374,
		"freelancers_needed": 4,
		"months_of_work": 2
	},
	{
		"id": 28,
		"company_name": "Fusce Dolor Quam Institute",
		"full_name": "Mariko",
		"location": "South Sudan",
		"annual_revenue": "€192,076",
		"email": "nascetur@euduiCum.com",
		"number_of_employees": 70710,
		"freelancers_needed": 5,
		"months_of_work": 5
	},
	{
		"id": 29,
		"company_name": "Proin Corp.",
		"full_name": "Leilani",
		"location": "Somalia",
		"annual_revenue": "€143,008",
		"email": "consequat@tempusscelerisque.com",
		"number_of_employees": 57390,
		"freelancers_needed": 6,
		"months_of_work": 4
	},
	{
		"id": 30,
		"company_name": "Et Euismod Institute",
		"full_name": "Jemima",
		"location": "Philippines",
		"annual_revenue": "€142,282",
		"email": "eu.dolor@fames.org",
		"number_of_employees": 86525,
		"freelancers_needed": 8,
		"months_of_work": 4
	},
	{
		"id": 31,
		"company_name": "Urna Vivamus Incorporated",
		"full_name": "Zena",
		"location": "South Georgia and The South Sandwich Islands",
		"annual_revenue": "€169,562",
		"email": "arcu@Fusce.ca",
		"number_of_employees": 68759,
		"freelancers_needed": 9,
		"months_of_work": 10
	},
	{
		"id": 32,
		"company_name": "Enim Commodo Hendrerit Inc.",
		"full_name": "Axel",
		"location": "Hong Kong",
		"annual_revenue": "€199,429",
		"email": "In.scelerisque.scelerisque@quis.edu",
		"number_of_employees": 91791,
		"freelancers_needed": 5,
		"months_of_work": 1
	},
	{
		"id": 33,
		"company_name": "Ullamcorper Limited",
		"full_name": "Josiah",
		"location": "Papua New Guinea",
		"annual_revenue": "€121,822",
		"email": "vitae.mauris.sit@vitaevelitegestas.edu",
		"number_of_employees": 23968,
		"freelancers_needed": 8,
		"months_of_work": 10
	},
	{
		"id": 34,
		"company_name": "Donec Tempus Lorem Corporation",
		"full_name": "Troy",
		"location": "Mozambique",
		"annual_revenue": "€163,931",
		"email": "ac.mattis@Aeneansed.com",
		"number_of_employees": 67642,
		"freelancers_needed": 1,
		"months_of_work": 4
	},
	{
		"id": 35,
		"company_name": "Arcu Curabitur Ut PC",
		"full_name": "Miriam",
		"location": "Philippines",
		"annual_revenue": "€148,349",
		"email": "ut@Crasdolor.net",
		"number_of_employees": 92703,
		"freelancers_needed": 5,
		"months_of_work": 10
	},
	{
		"id": 36,
		"company_name": "Montes Incorporated",
		"full_name": "Edan",
		"location": "French Guiana",
		"annual_revenue": "€121,722",
		"email": "non.cursus@vel.co.uk",
		"number_of_employees": 56266,
		"freelancers_needed": 4,
		"months_of_work": 3
	},
	{
		"id": 37,
		"company_name": "Duis PC",
		"full_name": "Emerson",
		"location": "Liberia",
		"annual_revenue": "€177,060",
		"email": "Nunc.mauris@Etiamligula.edu",
		"number_of_employees": 59517,
		"freelancers_needed": 3,
		"months_of_work": 1
	},
	{
		"id": 38,
		"company_name": "Scelerisque Neque Nullam Foundation",
		"full_name": "Rahim",
		"location": "Haiti",
		"annual_revenue": "€131,983",
		"email": "sociis.natoque.penatibus@porttitoreros.edu",
		"number_of_employees": 76132,
		"freelancers_needed": 5,
		"months_of_work": 2
	},
	{
		"id": 39,
		"company_name": "Fermentum Arcu Vestibulum LLC",
		"full_name": "Joelle",
		"location": "Paraguay",
		"annual_revenue": "€145,189",
		"email": "sed@pharetrasedhendrerit.org",
		"number_of_employees": 14252,
		"freelancers_needed": 3,
		"months_of_work": 7
	},
	{
		"id": 40,
		"company_name": "Sagittis Nullam Limited",
		"full_name": "Tasha",
		"location": "Mexico",
		"annual_revenue": "€178,134",
		"email": "pellentesque@natoquepenatibus.net",
		"number_of_employees": 83710,
		"freelancers_needed": 7,
		"months_of_work": 1
	},
	{
		"id": 41,
		"company_name": "Fringilla Porttitor Vulputate Inc.",
		"full_name": "Basil",
		"location": "Kazakhstan",
		"annual_revenue": "€152,780",
		"email": "parturient.montes.nascetur@musDonecdignissim.edu",
		"number_of_employees": 44856,
		"freelancers_needed": 1,
		"months_of_work": 3
	},
	{
		"id": 42,
		"company_name": "Nunc Interdum Limited",
		"full_name": "Chadwick",
		"location": "Poland",
		"annual_revenue": "€127,088",
		"email": "auctor.non.feugiat@neceleifendnon.co.uk",
		"number_of_employees": 42325,
		"freelancers_needed": 3,
		"months_of_work": 1
	},
	{
		"id": 43,
		"company_name": "Mollis Non Cursus Incorporated",
		"full_name": "Wayne",
		"location": "Slovenia",
		"annual_revenue": "€164,902",
		"email": "rhoncus@necligula.co.uk",
		"number_of_employees": 46082,
		"freelancers_needed": 9,
		"months_of_work": 4
	},
	{
		"id": 44,
		"company_name": "Phasellus Nulla Integer LLC",
		"full_name": "Ramona",
		"location": "Syria",
		"annual_revenue": "€129,589",
		"email": "in@scelerisquesedsapien.co.uk",
		"number_of_employees": 71962,
		"freelancers_needed": 7,
		"months_of_work": 2
	},
	{
		"id": 45,
		"company_name": "Dolor Nulla Corporation",
		"full_name": "Teegan",
		"location": "Saudi Arabia",
		"annual_revenue": "€136,043",
		"email": "cursus@lacinia.co.uk",
		"number_of_employees": 54072,
		"freelancers_needed": 7,
		"months_of_work": 9
	},
	{
		"id": 46,
		"company_name": "Gravida Mauris Corporation",
		"full_name": "Caesar",
		"location": "Serbia",
		"annual_revenue": "€166,153",
		"email": "magna.Praesent.interdum@elita.com",
		"number_of_employees": 77476,
		"freelancers_needed": 7,
		"months_of_work": 1
	},
	{
		"id": 47,
		"company_name": "Eget Metus Institute",
		"full_name": "Heather",
		"location": "Luxembourg",
		"annual_revenue": "€178,805",
		"email": "non.hendrerit@congueIn.edu",
		"number_of_employees": 61485,
		"freelancers_needed": 10,
		"months_of_work": 1
	},
	{
		"id": 48,
		"company_name": "Lorem Eget Mollis Limited",
		"full_name": "Wesley",
		"location": "Samoa",
		"annual_revenue": "€182,859",
		"email": "sociis@mattisornarelectus.net",
		"number_of_employees": 58412,
		"freelancers_needed": 4,
		"months_of_work": 8
	},
	{
		"id": 49,
		"company_name": "Fermentum Arcu Vestibulum Ltd",
		"full_name": "Candice",
		"location": "Mali",
		"annual_revenue": "€164,774",
		"email": "Cum@Nullam.co.uk",
		"number_of_employees": 82588,
		"freelancers_needed": 10,
		"months_of_work": 8
	},
	{
		"id": 50,
		"company_name": "Imperdiet Ornare In LLP",
		"full_name": "Alexis",
		"location": "Saint Martin",
		"annual_revenue": "€109,712",
		"email": "a@venenatisvelfaucibus.com",
		"number_of_employees": 8811,
		"freelancers_needed": 6,
		"months_of_work": 6
	},
	{
		"id": 51,
		"company_name": "Eget Massa PC",
		"full_name": "Scarlett",
		"location": "Mozambique",
		"annual_revenue": "€111,577",
		"email": "auctor@Donecnonjusto.com",
		"number_of_employees": 3305,
		"freelancers_needed": 3,
		"months_of_work": 6
	},
	{
		"id": 52,
		"company_name": "Mauris Corp.",
		"full_name": "Roary",
		"location": "Uzbekistan",
		"annual_revenue": "€155,924",
		"email": "nec@Duiscursus.ca",
		"number_of_employees": 34591,
		"freelancers_needed": 10,
		"months_of_work": 9
	},
	{
		"id": 53,
		"company_name": "A Consulting",
		"full_name": "Xanthus",
		"location": "Cyprus",
		"annual_revenue": "€188,883",
		"email": "eleifend@scelerisque.com",
		"number_of_employees": 6375,
		"freelancers_needed": 8,
		"months_of_work": 1
	},
	{
		"id": 54,
		"company_name": "In Sodales Foundation",
		"full_name": "Zeus",
		"location": "Niger",
		"annual_revenue": "€146,217",
		"email": "blandit.Nam.nulla@molestie.co.uk",
		"number_of_employees": 7914,
		"freelancers_needed": 6,
		"months_of_work": 2
	},
	{
		"id": 55,
		"company_name": "Egestas Industries",
		"full_name": "Quintessa",
		"location": "Burundi",
		"annual_revenue": "€115,986",
		"email": "ullamcorper.eu.euismod@Aliquamerat.org",
		"number_of_employees": 20125,
		"freelancers_needed": 9,
		"months_of_work": 3
	},
	{
		"id": 56,
		"company_name": "Vitae Semper Egestas LLP",
		"full_name": "Farrah",
		"location": "Pitcairn Islands",
		"annual_revenue": "€145,840",
		"email": "et.malesuada.fames@veliteu.com",
		"number_of_employees": 75633,
		"freelancers_needed": 1,
		"months_of_work": 3
	},
	{
		"id": 57,
		"company_name": "Euismod PC",
		"full_name": "Hadley",
		"location": "Holy See (Vatican City State)",
		"annual_revenue": "€105,955",
		"email": "ultrices.Duis.volutpat@Duis.com",
		"number_of_employees": 78146,
		"freelancers_needed": 5,
		"months_of_work": 10
	},
	{
		"id": 58,
		"company_name": "Lacus Aliquam Rutrum Corp.",
		"full_name": "Ina",
		"location": "Kiribati",
		"annual_revenue": "€196,945",
		"email": "Duis.at.lacus@nequesed.edu",
		"number_of_employees": 60187,
		"freelancers_needed": 7,
		"months_of_work": 4
	},
	{
		"id": 59,
		"company_name": "Imperdiet PC",
		"full_name": "Stewart",
		"location": "Northern Mariana Islands",
		"annual_revenue": "€181,014",
		"email": "lobortis@sodales.net",
		"number_of_employees": 61107,
		"freelancers_needed": 4,
		"months_of_work": 10
	},
	{
		"id": 60,
		"company_name": "Arcu Industries",
		"full_name": "Dawn",
		"location": "Montenegro",
		"annual_revenue": "€136,830",
		"email": "non.dapibus.rutrum@nulla.net",
		"number_of_employees": 59249,
		"freelancers_needed": 5,
		"months_of_work": 3
	},
	{
		"id": 61,
		"company_name": "Aenean Inc.",
		"full_name": "Stuart",
		"location": "Burkina Faso",
		"annual_revenue": "€152,079",
		"email": "et@ac.edu",
		"number_of_employees": 51343,
		"freelancers_needed": 9,
		"months_of_work": 2
	},
	{
		"id": 62,
		"company_name": "Nunc Ltd",
		"full_name": "Lee",
		"location": "Saint Helena, Ascension and Tristan da Cunha",
		"annual_revenue": "€107,658",
		"email": "libero.Proin@ac.co.uk",
		"number_of_employees": 57408,
		"freelancers_needed": 10,
		"months_of_work": 4
	},
	{
		"id": 63,
		"company_name": "Vulputate Mauris Sagittis Company",
		"full_name": "William",
		"location": "Malaysia",
		"annual_revenue": "€184,743",
		"email": "Mauris.eu@magnisdisparturient.com",
		"number_of_employees": 17425,
		"freelancers_needed": 10,
		"months_of_work": 1
	},
	{
		"id": 64,
		"company_name": "Lorem Eget Mollis Ltd",
		"full_name": "Tate",
		"location": "Greece",
		"annual_revenue": "€106,311",
		"email": "cursus.luctus.ipsum@DonecnibhQuisque.com",
		"number_of_employees": 61698,
		"freelancers_needed": 5,
		"months_of_work": 8
	},
	{
		"id": 65,
		"company_name": "Natoque Penatibus Industries",
		"full_name": "Isaac",
		"location": "Brazil",
		"annual_revenue": "€190,009",
		"email": "cursus.Integer@ornarelibero.edu",
		"number_of_employees": 4659,
		"freelancers_needed": 5,
		"months_of_work": 5
	},
	{
		"id": 66,
		"company_name": "Enim Gravida Inc.",
		"full_name": "Ishmael",
		"location": "Brazil",
		"annual_revenue": "€149,901",
		"email": "mauris@pellentesquetellussem.edu",
		"number_of_employees": 45150,
		"freelancers_needed": 3,
		"months_of_work": 5
	},
	{
		"id": 67,
		"company_name": "Libero Proin Mi LLC",
		"full_name": "Buckminster",
		"location": "Finland",
		"annual_revenue": "€102,848",
		"email": "Mauris@ut.com",
		"number_of_employees": 49916,
		"freelancers_needed": 2,
		"months_of_work": 3
	},
	{
		"id": 68,
		"company_name": "Elementum At Egestas Corp.",
		"full_name": "Alyssa",
		"location": "Denmark",
		"annual_revenue": "€156,894",
		"email": "purus@inaliquetlobortis.org",
		"number_of_employees": 65684,
		"freelancers_needed": 10,
		"months_of_work": 1
	},
	{
		"id": 69,
		"company_name": "Vitae Aliquet Incorporated",
		"full_name": "Irma",
		"location": "Morocco",
		"annual_revenue": "€120,323",
		"email": "Lorem.ipsum.dolor@eu.com",
		"number_of_employees": 64080,
		"freelancers_needed": 2,
		"months_of_work": 4
	},
	{
		"id": 70,
		"company_name": "Commodo Hendrerit Donec Limited",
		"full_name": "Cheyenne",
		"location": "American Samoa",
		"annual_revenue": "€120,408",
		"email": "Sed.congue@ac.com",
		"number_of_employees": 1723,
		"freelancers_needed": 4,
		"months_of_work": 3
	},
	{
		"id": 71,
		"company_name": "Nisl Maecenas Malesuada Associates",
		"full_name": "Katelyn",
		"location": "Belarus",
		"annual_revenue": "€142,833",
		"email": "orci.Donec.nibh@eleifend.com",
		"number_of_employees": 28989,
		"freelancers_needed": 5,
		"months_of_work": 1
	},
	{
		"id": 72,
		"company_name": "Id PC",
		"full_name": "Amena",
		"location": "Saint Lucia",
		"annual_revenue": "€127,101",
		"email": "elit@eleifendegestas.com",
		"number_of_employees": 51361,
		"freelancers_needed": 8,
		"months_of_work": 8
	},
	{
		"id": 73,
		"company_name": "Sed Dictum Eleifend PC",
		"full_name": "Aurora",
		"location": "Cayman Islands",
		"annual_revenue": "€197,567",
		"email": "commodo@Integer.org",
		"number_of_employees": 30194,
		"freelancers_needed": 1,
		"months_of_work": 10
	},
	{
		"id": 74,
		"company_name": "Ligula Aenean PC",
		"full_name": "Cameran",
		"location": "Iraq",
		"annual_revenue": "€196,464",
		"email": "Nulla@velvenenatis.net",
		"number_of_employees": 93252,
		"freelancers_needed": 3,
		"months_of_work": 1
	},
	{
		"id": 75,
		"company_name": "Mauris Foundation",
		"full_name": "Allegra",
		"location": "Iceland",
		"annual_revenue": "€113,187",
		"email": "lectus.sit@hendreritDonec.org",
		"number_of_employees": 49658,
		"freelancers_needed": 4,
		"months_of_work": 2
	},
	{
		"id": 76,
		"company_name": "Curabitur Vel Incorporated",
		"full_name": "Kyla",
		"location": "Uruguay",
		"annual_revenue": "€134,895",
		"email": "luctus.vulputate.nisi@nec.org",
		"number_of_employees": 1821,
		"freelancers_needed": 6,
		"months_of_work": 7
	},
	{
		"id": 77,
		"company_name": "Fusce Institute",
		"full_name": "Madison",
		"location": "Virgin Islands, British",
		"annual_revenue": "€197,995",
		"email": "erat.neque.non@convallisdolor.com",
		"number_of_employees": 55111,
		"freelancers_needed": 6,
		"months_of_work": 6
	},
	{
		"id": 78,
		"company_name": "Ullamcorper Duis At Company",
		"full_name": "Miranda",
		"location": "Iraq",
		"annual_revenue": "€189,554",
		"email": "diam.dictum.sapien@faucibusleoin.ca",
		"number_of_employees": 48717,
		"freelancers_needed": 6,
		"months_of_work": 1
	},
	{
		"id": 79,
		"company_name": "A Ultricies Adipiscing Inc.",
		"full_name": "Elizabeth",
		"location": "Algeria",
		"annual_revenue": "€123,513",
		"email": "pharetra.felis@in.com",
		"number_of_employees": 16808,
		"freelancers_needed": 3,
		"months_of_work": 5
	},
	{
		"id": 80,
		"company_name": "Sit Associates",
		"full_name": "Sigourney",
		"location": "Turkey",
		"annual_revenue": "€198,331",
		"email": "dictum@tortor.com",
		"number_of_employees": 56930,
		"freelancers_needed": 9,
		"months_of_work": 10
	},
	{
		"id": 81,
		"company_name": "Ipsum Donec Sollicitudin Institute",
		"full_name": "Brian",
		"location": "Sierra Leone",
		"annual_revenue": "€134,921",
		"email": "Quisque@urnajusto.net",
		"number_of_employees": 64205,
		"freelancers_needed": 6,
		"months_of_work": 9
	},
	{
		"id": 82,
		"company_name": "Imperdiet Ornare In Limited",
		"full_name": "Catherine",
		"location": "Samoa",
		"annual_revenue": "€111,154",
		"email": "in.molestie.tortor@sempereratin.edu",
		"number_of_employees": 19644,
		"freelancers_needed": 8,
		"months_of_work": 1
	},
	{
		"id": 83,
		"company_name": "Odio Phasellus Inc.",
		"full_name": "Lynn",
		"location": "Israel",
		"annual_revenue": "€199,112",
		"email": "conubia.nostra@necurnasuscipit.co.uk",
		"number_of_employees": 17136,
		"freelancers_needed": 2,
		"months_of_work": 8
	},
	{
		"id": 84,
		"company_name": "Mattis Corp.",
		"full_name": "Hakeem",
		"location": "Thailand",
		"annual_revenue": "€190,144",
		"email": "nibh.Quisque.nonummy@Aeneanegetmagna.com",
		"number_of_employees": 93317,
		"freelancers_needed": 8,
		"months_of_work": 5
	},
	{
		"id": 85,
		"company_name": "Leo Elementum Sem Company",
		"full_name": "Blake",
		"location": "Svalbard and Jan Mayen Islands",
		"annual_revenue": "€159,488",
		"email": "risus.Donec@sagittissemper.ca",
		"number_of_employees": 44443,
		"freelancers_needed": 9,
		"months_of_work": 3
	},
	{
		"id": 86,
		"company_name": "Mauris Id Limited",
		"full_name": "Drew",
		"location": "Peru",
		"annual_revenue": "€131,670",
		"email": "In.faucibus.Morbi@at.co.uk",
		"number_of_employees": 35309,
		"freelancers_needed": 4,
		"months_of_work": 8
	},
	{
		"id": 87,
		"company_name": "Elementum Dui PC",
		"full_name": "Herrod",
		"location": "Jersey",
		"annual_revenue": "€143,197",
		"email": "lorem.eu@nullaanteiaculis.co.uk",
		"number_of_employees": 63065,
		"freelancers_needed": 1,
		"months_of_work": 4
	},
	{
		"id": 88,
		"company_name": "Ante Dictum Associates",
		"full_name": "Kiayada",
		"location": "Morocco",
		"annual_revenue": "€116,105",
		"email": "consectetuer@tempor.org",
		"number_of_employees": 34633,
		"freelancers_needed": 7,
		"months_of_work": 10
	},
	{
		"id": 89,
		"company_name": "Ornare Associates",
		"full_name": "Lacy",
		"location": "Georgia",
		"annual_revenue": "€123,529",
		"email": "euismod.est.arcu@Vestibulum.edu",
		"number_of_employees": 54437,
		"freelancers_needed": 2,
		"months_of_work": 4
	},
	{
		"id": 90,
		"company_name": "Et Malesuada Company",
		"full_name": "Noah",
		"location": "Grenada",
		"annual_revenue": "€120,885",
		"email": "erat.volutpat.Nulla@acturpisegestas.edu",
		"number_of_employees": 47111,
		"freelancers_needed": 9,
		"months_of_work": 2
	},
	{
		"id": 91,
		"company_name": "Senectus Et Associates",
		"full_name": "Adria",
		"location": "Costa Rica",
		"annual_revenue": "€175,579",
		"email": "luctus.sit@egestasAliquam.com",
		"number_of_employees": 12264,
		"freelancers_needed": 1,
		"months_of_work": 9
	},
	{
		"id": 92,
		"company_name": "Penatibus Inc.",
		"full_name": "Alice",
		"location": "Italy",
		"annual_revenue": "€106,434",
		"email": "natoque.penatibus@AeneanmassaInteger.com",
		"number_of_employees": 82978,
		"freelancers_needed": 8,
		"months_of_work": 6
	},
	{
		"id": 93,
		"company_name": "Aliquam Enim Nec LLC",
		"full_name": "Ryan",
		"location": "Israel",
		"annual_revenue": "€100,564",
		"email": "at@liberoProin.com",
		"number_of_employees": 50832,
		"freelancers_needed": 6,
		"months_of_work": 7
	},
	{
		"id": 94,
		"company_name": "Aliquam Nec Industries",
		"full_name": "Rafael",
		"location": "Antarctica",
		"annual_revenue": "€114,577",
		"email": "varius.orci@nequenonquam.net",
		"number_of_employees": 52537,
		"freelancers_needed": 7,
		"months_of_work": 10
	},
	{
		"id": 95,
		"company_name": "Sit Amet Metus LLP",
		"full_name": "Lila",
		"location": "Guatemala",
		"annual_revenue": "€115,685",
		"email": "lorem@hendreritidante.co.uk",
		"number_of_employees": 56530,
		"freelancers_needed": 9,
		"months_of_work": 4
	},
	{
		"id": 96,
		"company_name": "Auctor Inc.",
		"full_name": "Drake",
		"location": "Guinea",
		"annual_revenue": "€152,552",
		"email": "erat.vitae.risus@Donectempor.net",
		"number_of_employees": 58360,
		"freelancers_needed": 4,
		"months_of_work": 4
	},
	{
		"id": 97,
		"company_name": "Tincidunt Tempus PC",
		"full_name": "Derek",
		"location": "Virgin Islands, British",
		"annual_revenue": "€189,419",
		"email": "mi.Aliquam@egetlacus.ca",
		"number_of_employees": 14327,
		"freelancers_needed": 1,
		"months_of_work": 8
	},
	{
		"id": 98,
		"company_name": "Erat In Consectetuer Corporation",
		"full_name": "Thane",
		"location": "Switzerland",
		"annual_revenue": "€122,138",
		"email": "quam@Nuncut.ca",
		"number_of_employees": 62924,
		"freelancers_needed": 7,
		"months_of_work": 5
	},
	{
		"id": 99,
		"company_name": "Accumsan Laoreet Ipsum Institute",
		"full_name": "Quin",
		"location": "Palau",
		"annual_revenue": "€106,840",
		"email": "aliquam.arcu@lectus.com",
		"number_of_employees": 80425,
		"freelancers_needed": 5,
		"months_of_work": 10
	},
	{
		"id": 100,
		"company_name": "Lacus Mauris Company",
		"full_name": "Marvin",
		"location": "Malta",
		"annual_revenue": "€111,032",
		"email": "nisi.Aenean.eget@mi.edu",
		"number_of_employees": 80742,
		"freelancers_needed": 4,
		"months_of_work": 2
	}
]
